### ISSUE TITLE
Combine Hypothetical Budget Change & COS Change into one calculator

### ISSUE THREAD

**Issue by shilojones** [statbid/calculators#6]
We'd like to combine these two calculators into one calculator and create a toggle to allow the user to either enter in a budget change, COS or ROAS change.

![image](https://github.com/user-attachments/assets/8c0c98fb-c9e0-41ee-a596-4ce865b5ee21)

**Comment by artemiystlr** [comment]
Here's a basic .html file with a layout for the new design.
[cos_roas_calculator.html.zip](https://github.com/user-attachments/files/17356360/cos_roas_calculator.html.zip)

Had to compress it, since Github doesn't allow to attach .html files.

**Comment by shilojones** [comment]
@arfaouisabeur - I know @artemiystlr is finishing up this and will post the figma mockups soon, but this is what the new UI is looking like.

![image](https://github.com/user-attachments/assets/6f38d025-38d0-4284-83a7-1abf054e485b)
